// Star Citizen ship database — auto-fills manufacturer, class, and role in Fleet registry
// Format: { name, manufacturer, size, role }

export const SC_SHIPS = [
  // ── AEGIS DYNAMICS ──
  { name: 'Avenger Stalker', manufacturer: 'Aegis Dynamics', size: 'Small', role: 'Interdiction' },
  { name: 'Avenger Titan', manufacturer: 'Aegis Dynamics', size: 'Small', role: 'Light Freight' },
  { name: 'Avenger Titan Renegade', manufacturer: 'Aegis Dynamics', size: 'Small', role: 'Light Freight' },
  { name: 'Avenger Warlock', manufacturer: 'Aegis Dynamics', size: 'Small', role: 'Interdiction EMP' },
  { name: 'Eclipse', manufacturer: 'Aegis Dynamics', size: 'Medium', role: 'Stealth Bomber' },
  { name: 'Gladius', manufacturer: 'Aegis Dynamics', size: 'Small', role: 'Light Fighter' },
  { name: 'Gladius Valiant', manufacturer: 'Aegis Dynamics', size: 'Small', role: 'Light Fighter' },
  { name: 'Hammerhead', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Heavy Gunship' },
  { name: 'Idris-M', manufacturer: 'Aegis Dynamics', size: 'Capital', role: 'Frigate' },
  { name: 'Idris-P', manufacturer: 'Aegis Dynamics', size: 'Capital', role: 'Frigate' },
  { name: 'Javelin', manufacturer: 'Aegis Dynamics', size: 'Capital', role: 'Destroyer' },
  { name: 'Nautilus', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Minelayer' },
  { name: 'Reclaimer', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Salvage' },
  { name: 'Redeemer', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Gunship' },
  { name: 'Retaliator Bomber', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Heavy Bomber' },
  { name: 'Sabre', manufacturer: 'Aegis Dynamics', size: 'Medium', role: 'Stealth Fighter' },
  { name: 'Sabre Comet', manufacturer: 'Aegis Dynamics', size: 'Medium', role: 'Stealth Fighter' },
  { name: 'Sabre Raven', manufacturer: 'Aegis Dynamics', size: 'Medium', role: 'Stealth Fighter' },
  { name: 'Vanguard Harbinger', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Heavy Bomber' },
  { name: 'Vanguard Hoplite', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Dropship' },
  { name: 'Vanguard Sentinel', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Electronic Warfare' },
  { name: 'Vanguard Warden', manufacturer: 'Aegis Dynamics', size: 'Large', role: 'Heavy Fighter' },
  { name: 'Vulcan', manufacturer: 'Aegis Dynamics', size: 'Medium', role: 'Support - Repair/Refuel' },

  // ── ANVIL AEROSPACE ──
  { name: 'Arrow', manufacturer: 'Anvil Aerospace', size: 'Small', role: 'Light Fighter' },
  { name: 'Ballista', manufacturer: 'Anvil Aerospace', size: 'Vehicle', role: 'Anti-Aircraft' },
  { name: 'C8 Pisces', manufacturer: 'Anvil Aerospace', size: 'Small', role: 'Snub / Utility' },
  { name: 'C8X Pisces Expedition', manufacturer: 'Anvil Aerospace', size: 'Small', role: 'Snub / Utility' },
  { name: 'Carrack', manufacturer: 'Anvil Aerospace', size: 'Large', role: 'Exploration' },
  { name: 'Carrack Expedition', manufacturer: 'Anvil Aerospace', size: 'Large', role: 'Exploration' },
  { name: 'Centurion', manufacturer: 'Anvil Aerospace', size: 'Vehicle', role: 'Anti-Aircraft' },
  { name: 'Crucible', manufacturer: 'Anvil Aerospace', size: 'Large', role: 'Repair' },
  { name: 'F7C Hornet', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Medium Fighter' },
  { name: 'F7C Hornet Wildfire', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Medium Fighter' },
  { name: 'F7C-M Super Hornet', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'F7C-R Hornet Tracker', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Tracker' },
  { name: 'F7C-S Hornet Ghost', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Stealth Fighter' },
  { name: 'F7A Hornet Mk II', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Medium Fighter' },
  { name: 'F8C Lightning', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'Gladiator', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Light Bomber' },
  { name: 'Hawk', manufacturer: 'Anvil Aerospace', size: 'Small', role: 'Bounty Hunter' },
  { name: 'Hurricane', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'Legionnaire', manufacturer: 'Anvil Aerospace', size: 'Medium', role: 'Boarding Ship' },
  { name: 'Liberator', manufacturer: 'Anvil Aerospace', size: 'Large', role: 'Vehicle Transport' },
  { name: 'Spartan', manufacturer: 'Anvil Aerospace', size: 'Vehicle', role: 'APC' },
  { name: 'Terrapin', manufacturer: 'Anvil Aerospace', size: 'Small', role: 'Pathfinder' },
  { name: 'Valkyrie', manufacturer: 'Anvil Aerospace', size: 'Large', role: 'Dropship' },

  // ── ARGO ASTRONAUTICS ──
  { name: 'ARGO ATLS', manufacturer: 'ARGO Astronautics', size: 'Vehicle', role: 'Cargo Mech' },
  { name: 'ARGO Mole', manufacturer: 'ARGO Astronautics', size: 'Large', role: 'Multi-Crew Mining' },
  { name: 'ARGO MPUV-1C Cargo', manufacturer: 'ARGO Astronautics', size: 'Small', role: 'Utility Transport' },
  { name: 'ARGO MPUV-1P Personnel', manufacturer: 'ARGO Astronautics', size: 'Small', role: 'Personnel Transport' },
  { name: 'ARGO RAFT', manufacturer: 'ARGO Astronautics', size: 'Medium', role: 'Light Freight' },
  { name: 'ARGO SRV', manufacturer: 'ARGO Astronautics', size: 'Small', role: 'Towing / Recovery' },

  // ── BANU ──
  { name: 'Banu Defender', manufacturer: 'Banu', size: 'Medium', role: 'Medium Fighter' },
  { name: 'Banu Merchantman', manufacturer: 'Banu', size: 'Capital', role: 'Trading / Commerce' },

  // ── CONSOLIDATED OUTLAND ──
  { name: 'Mustang Alpha', manufacturer: 'Consolidated Outland', size: 'Small', role: 'Starter' },
  { name: 'Mustang Beta', manufacturer: 'Consolidated Outland', size: 'Small', role: 'Pathfinder' },
  { name: 'Mustang Delta', manufacturer: 'Consolidated Outland', size: 'Small', role: 'Light Fighter' },
  { name: 'Mustang Gamma', manufacturer: 'Consolidated Outland', size: 'Small', role: 'Racer' },
  { name: 'Mustang Omega', manufacturer: 'Consolidated Outland', size: 'Small', role: 'Racer' },
  { name: 'Nomad', manufacturer: 'Consolidated Outland', size: 'Small', role: 'Light Freight' },
  { name: 'Pioneer', manufacturer: 'Consolidated Outland', size: 'Capital', role: 'Construction' },

  // ── CRUSADER INDUSTRIES ──
  { name: 'A2 Hercules Starlifter', manufacturer: 'Crusader Industries', size: 'Large', role: 'Transport Gunship' },
  { name: 'Ares Star Fighter Inferno', manufacturer: 'Crusader Industries', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'Ares Star Fighter Ion', manufacturer: 'Crusader Industries', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'C2 Hercules Starlifter', manufacturer: 'Crusader Industries', size: 'Large', role: 'Heavy Freight' },
  { name: 'Genesis Starliner', manufacturer: 'Crusader Industries', size: 'Large', role: 'Passenger Transport' },
  { name: 'M2 Hercules Starlifter', manufacturer: 'Crusader Industries', size: 'Large', role: 'Military Transport' },
  { name: 'Mercury Star Runner', manufacturer: 'Crusader Industries', size: 'Large', role: 'Data Running / Freight' },
  { name: 'Spirit A1', manufacturer: 'Crusader Industries', size: 'Medium', role: 'Light Bomber' },
  { name: 'Spirit C1', manufacturer: 'Crusader Industries', size: 'Medium', role: 'Light Freight' },
  { name: 'Spirit E1', manufacturer: 'Crusader Industries', size: 'Medium', role: 'Passenger Transport' },

  // ── DRAKE INTERPLANETARY ──
  { name: 'Buccaneer', manufacturer: 'Drake Interplanetary', size: 'Small', role: 'Medium Fighter' },
  { name: 'Caterpillar', manufacturer: 'Drake Interplanetary', size: 'Large', role: 'Heavy Freight' },
  { name: 'Corsair', manufacturer: 'Drake Interplanetary', size: 'Large', role: 'Exploration' },
  { name: 'Cutlass Black', manufacturer: 'Drake Interplanetary', size: 'Medium', role: 'Medium Freight' },
  { name: 'Cutlass Blue', manufacturer: 'Drake Interplanetary', size: 'Medium', role: 'Interdiction' },
  { name: 'Cutlass Red', manufacturer: 'Drake Interplanetary', size: 'Medium', role: 'Medical Support' },
  { name: 'Cutlass Steel', manufacturer: 'Drake Interplanetary', size: 'Medium', role: 'Troop Transport' },
  { name: 'Dragonfly Black', manufacturer: 'Drake Interplanetary', size: 'Vehicle', role: 'Hoverbike' },
  { name: 'Dragonfly Yellowjacket', manufacturer: 'Drake Interplanetary', size: 'Vehicle', role: 'Hoverbike' },
  { name: 'Herald', manufacturer: 'Drake Interplanetary', size: 'Small', role: 'Data Running' },
  { name: 'Ironclad', manufacturer: 'Drake Interplanetary', size: 'Large', role: 'Heavy Freight / Industrial' },
  { name: 'Kraken', manufacturer: 'Drake Interplanetary', size: 'Capital', role: 'Carrier' },
  { name: 'Kraken Privateer', manufacturer: 'Drake Interplanetary', size: 'Capital', role: 'Carrier / Commerce' },
  { name: 'Mule', manufacturer: 'Drake Interplanetary', size: 'Vehicle', role: 'Utility' },
  { name: 'Vulture', manufacturer: 'Drake Interplanetary', size: 'Small', role: 'Salvage' },
  { name: 'Cutter', manufacturer: 'Drake Interplanetary', size: 'Small', role: 'Starter / Light Freight' },
  { name: 'Cutter Rambler', manufacturer: 'Drake Interplanetary', size: 'Small', role: 'Starter / Exploration' },
  { name: 'Cutter Scout', manufacturer: 'Drake Interplanetary', size: 'Small', role: 'Starter / Scout' },

  // ── ESPERIA ──
  { name: 'Esperia Blade', manufacturer: 'Esperia', size: 'Medium', role: 'Light Fighter (Replica)' },
  { name: 'Esperia Glaive', manufacturer: 'Esperia', size: 'Medium', role: 'Heavy Fighter (Replica)' },
  { name: 'Esperia Prowler', manufacturer: 'Esperia', size: 'Medium', role: 'Dropship (Replica)' },
  { name: 'Esperia Talon', manufacturer: 'Esperia', size: 'Small', role: 'Light Fighter (Replica)' },
  { name: 'Esperia Talon Shrike', manufacturer: 'Esperia', size: 'Small', role: 'Light Fighter (Replica)' },

  // ── GATAC ──
  { name: 'Gatac Railen', manufacturer: 'Gatac', size: 'Large', role: 'Alien Freight' },
  { name: 'Gatac Syulen', manufacturer: 'Gatac', size: 'Small', role: 'Alien Touring' },

  // ── KRUGER INTERGALACTIC ──
  { name: 'P-52 Merlin', manufacturer: 'Kruger Intergalactic', size: 'Small', role: 'Snub Fighter' },
  { name: 'P-72 Archimedes', manufacturer: 'Kruger Intergalactic', size: 'Small', role: 'Snub Racer' },
  { name: 'P-72 Archimedes Emerald', manufacturer: 'Kruger Intergalactic', size: 'Small', role: 'Snub Racer' },

  // ── MIRAI ──
  { name: 'Fury', manufacturer: 'Mirai', size: 'Small', role: 'Light Fighter' },
  { name: 'Fury LX', manufacturer: 'Mirai', size: 'Small', role: 'Light Fighter' },
  { name: 'Fury MX', manufacturer: 'Mirai', size: 'Small', role: 'Light Fighter' },
  { name: 'Guardian', manufacturer: 'Mirai', size: 'Small', role: 'Light Fighter' },
  { name: 'Pulse', manufacturer: 'Mirai', size: 'Small', role: 'Light Fighter' },
  { name: 'Pulse LX', manufacturer: 'Mirai', size: 'Small', role: 'Light Fighter' },

  // ── MISC ──
  { name: 'Freelancer', manufacturer: 'MISC', size: 'Medium', role: 'Medium Freight' },
  { name: 'Freelancer DUR', manufacturer: 'MISC', size: 'Medium', role: 'Exploration' },
  { name: 'Freelancer MAX', manufacturer: 'MISC', size: 'Medium', role: 'Medium Freight' },
  { name: 'Freelancer MIS', manufacturer: 'MISC', size: 'Medium', role: 'Gunship' },
  { name: 'Hull A', manufacturer: 'MISC', size: 'Small', role: 'Light Freight' },
  { name: 'Hull B', manufacturer: 'MISC', size: 'Medium', role: 'Medium Freight' },
  { name: 'Hull C', manufacturer: 'MISC', size: 'Large', role: 'Heavy Freight' },
  { name: 'Hull D', manufacturer: 'MISC', size: 'Large', role: 'Bulk Freight' },
  { name: 'Hull E', manufacturer: 'MISC', size: 'Capital', role: 'Super Freight' },
  { name: 'Endeavor', manufacturer: 'MISC', size: 'Capital', role: 'Research / Science' },
  { name: 'Expanse', manufacturer: 'MISC', size: 'Large', role: 'Gas Refinery' },
  { name: 'Prospector', manufacturer: 'MISC', size: 'Small', role: 'Mining' },
  { name: 'Razor', manufacturer: 'MISC', size: 'Small', role: 'Racer' },
  { name: 'Razor EX', manufacturer: 'MISC', size: 'Small', role: 'Stealth Racer' },
  { name: 'Razor LX', manufacturer: 'MISC', size: 'Small', role: 'Racer' },
  { name: 'Reliant Kore', manufacturer: 'MISC', size: 'Small', role: 'Light Freight' },
  { name: 'Reliant Mako', manufacturer: 'MISC', size: 'Small', role: 'News / Reporting' },
  { name: 'Reliant Sen', manufacturer: 'MISC', size: 'Small', role: 'Science / Research' },
  { name: 'Reliant Tana', manufacturer: 'MISC', size: 'Small', role: 'Light Fighter' },
  { name: 'Starfarer', manufacturer: 'MISC', size: 'Large', role: 'Refueling' },
  { name: 'Starfarer Gemini', manufacturer: 'MISC', size: 'Large', role: 'Military Refueling' },
  { name: 'Starlancer MAX', manufacturer: 'MISC', size: 'Large', role: 'Heavy Freight' },
  { name: 'Starlancer TAC', manufacturer: 'MISC', size: 'Large', role: 'Military Transport' },
  { name: 'Odyssey', manufacturer: 'MISC', size: 'Capital', role: 'Deep Space Explorer' },

  // ── ORIGIN JUMPWORKS ──
  { name: '100i', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Starter / Touring' },
  { name: '125a', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Light Fighter' },
  { name: '135c', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Light Freight' },
  { name: '300i', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Touring' },
  { name: '315p', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Pathfinder' },
  { name: '325a', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Interdiction' },
  { name: '350r', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Racing' },
  { name: '400i', manufacturer: 'Origin Jumpworks', size: 'Large', role: 'Pathfinder' },
  { name: '600i Explorer', manufacturer: 'Origin Jumpworks', size: 'Large', role: 'Expedition' },
  { name: '600i Touring', manufacturer: 'Origin Jumpworks', size: 'Large', role: 'Touring' },
  { name: '600i Executive', manufacturer: 'Origin Jumpworks', size: 'Large', role: 'Expedition' },
  { name: '85X', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Touring Snub' },
  { name: '890 Jump', manufacturer: 'Origin Jumpworks', size: 'Capital', role: 'Luxury Touring' },
  { name: 'M50 Interceptor', manufacturer: 'Origin Jumpworks', size: 'Small', role: 'Racer / Interceptor' },
  { name: 'X1 Base', manufacturer: 'Origin Jumpworks', size: 'Vehicle', role: 'Hoverbike' },
  { name: 'X1 Force', manufacturer: 'Origin Jumpworks', size: 'Vehicle', role: 'Hoverbike' },
  { name: 'X1 Velocity', manufacturer: 'Origin Jumpworks', size: 'Vehicle', role: 'Hoverbike' },

  // ── RSI ──
  { name: 'Aurora CL', manufacturer: 'Roberts Space Industries', size: 'Small', role: 'Light Freight' },
  { name: 'Aurora ES', manufacturer: 'Roberts Space Industries', size: 'Small', role: 'Starter / Pathfinder' },
  { name: 'Aurora LN', manufacturer: 'Roberts Space Industries', size: 'Small', role: 'Light Fighter' },
  { name: 'Aurora LX', manufacturer: 'Roberts Space Industries', size: 'Small', role: 'Pathfinder' },
  { name: 'Aurora MR', manufacturer: 'Roberts Space Industries', size: 'Small', role: 'Starter / Light Fighter' },
  { name: 'Aurora MK2', manufacturer: 'Roberts Space Industries', size: 'Small', role: 'Starter' },
  { name: 'Constellation Andromeda', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Multi-Role' },
  { name: 'Constellation Aquila', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Exploration' },
  { name: 'Constellation Phoenix', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Luxury Touring' },
  { name: 'Constellation Taurus', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Heavy Freight' },
  { name: 'Galaxy', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Modular Multi-Role' },
  { name: 'Mantis', manufacturer: 'Roberts Space Industries', size: 'Medium', role: 'Interdiction' },
  { name: 'Orion', manufacturer: 'Roberts Space Industries', size: 'Capital', role: 'Industrial Mining' },
  { name: 'Perseus', manufacturer: 'Roberts Space Industries', size: 'Capital', role: 'Heavy Gunship' },
  { name: 'Polaris', manufacturer: 'Roberts Space Industries', size: 'Capital', role: 'Corvette' },
  { name: 'Scorpius', manufacturer: 'Roberts Space Industries', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'Scorpius Antares', manufacturer: 'Roberts Space Industries', size: 'Medium', role: 'Heavy Fighter' },
  { name: 'Zeus Mk II CL', manufacturer: 'Roberts Space Industries', size: 'Medium', role: 'Light Freight' },
  { name: 'Zeus Mk II ES', manufacturer: 'Roberts Space Industries', size: 'Medium', role: 'Starter' },
  { name: 'Zeus Mk II MR', manufacturer: 'Roberts Space Industries', size: 'Medium', role: 'Multi-Role' },
  { name: 'Apollo Medivac', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Medical' },
  { name: 'Apollo Triage', manufacturer: 'Roberts Space Industries', size: 'Large', role: 'Medical' },

  // ── TUMBRIL ──
  { name: 'Cyclone', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Exploration Buggy' },
  { name: 'Cyclone AA', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Anti-Aircraft Buggy' },
  { name: 'Cyclone MT', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Militia Buggy' },
  { name: 'Cyclone RC', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Racing Buggy' },
  { name: 'Cyclone RN', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Recon Buggy' },
  { name: 'Cyclone TR', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Transport Buggy' },
  { name: 'Nova Tank', manufacturer: 'Tumbril', size: 'Vehicle', role: 'Main Battle Tank' },
  { name: 'Storm', manufacturer: 'Tumbril', size: 'Vehicle', role: 'AA Platform' },
  { name: 'Storm AA', manufacturer: 'Tumbril', size: 'Vehicle', role: 'AA Platform' },

  // ── GREYCAT INDUSTRIAL ──
  { name: 'Greycat PTV', manufacturer: 'Greycat Industrial', size: 'Vehicle', role: 'Personal Transport' },
  { name: 'Greycat ROC', manufacturer: 'Greycat Industrial', size: 'Vehicle', role: 'Mining Vehicle' },
  { name: 'Greycat ROC-DS', manufacturer: 'Greycat Industrial', size: 'Vehicle', role: 'Dual Mining Vehicle' },
  { name: 'Greycat STV', manufacturer: 'Greycat Industrial', size: 'Vehicle', role: 'Multi-Tool Vehicle' },

  // ── AOPOA ──
  { name: 'Khartu-Al', manufacturer: 'Aopoa', size: 'Medium', role: 'Alien Scout' },
  { name: 'Nox', manufacturer: 'Aopoa', size: 'Vehicle', role: 'Alien Hoverbike' },
  { name: 'Nox Kue', manufacturer: 'Aopoa', size: 'Vehicle', role: 'Alien Hoverbike' },
  { name: 'San\'tok.yāi', manufacturer: 'Aopoa', size: 'Medium', role: 'Alien Heavy Fighter' },
].sort((a, b) => a.name.localeCompare(b.name))

export const SC_MANUFACTURERS = [...new Set(SC_SHIPS.map(s => s.manufacturer))].sort()
